#Druid 数据库连接池配置
db:
  driver-class-name: com.mysql.cj.jdbc.Driver
  #连接数初始化大小，最小，最大
  initialSize: 5
  min-idle: 5
  max-active: 20
  # 配置获取连接等待超时的时间
  max-wait-millis: 60000
  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
  time-between-eviction-runs-millis: 3600000
  # 配置一个连接在池中最小生存的时间，单位是毫秒
  min-evictable-idle-time-millis: 3600000
  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
  filters: slf4j,wall,stat
  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
  connection-properties: 'defaultRowPrefetch=5000;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500'
  # 合并多个DruidDataSource的监控数据
  use-global-data-source-stat: true
  #校验SQL
  validation-query: SELECT 'x'
  test-while-idle: true
  test-on-borrow: true
  test-on-return: false

datasource:
  hrm:
    url: jdbc:mysql://127.0.0.1/hrm?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
  domain:
    url: jdbc:mysql://127.0.0.1/hrm?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root





feign:
  okhttp:
    enabled: true
